services:
  ubuntu-sshd:
    image: ubuntu-sshd:focal
    command: ["--uid", "1000", "--user", "zhangzhong", "--passwd", "zhangzhong"]
    container_name: zz-test
    hostname: zz-test
    volumes:
     - ./home:/home/zhangzhong
    ports:
      - "23122:22"
    restart: always