version: "3.9"
services:
  fedora-sshd:
    image: fedora-sshd
    command: ["--user", "$USER", "--sudo", "nopasswd"]
    container_name: fedora-sshd
    hostname: fedora-sshd
    volumes:
      - ./home:/home/$USER
    ports:
      - "22"
    restart: on-failure
