version: "3.9"
services:
  ubuntu-sshd:
    image: ubuntu-sshd:focal
    command: ["--uid", "1000", "--user", "zhangzhong", "--passwd", "zhangzhong" , "--sudo", "nopasswd"]
    container_name: ubuntu-sshd
    hostname: ubuntu-sshd
    volumes:
     - ./home:/home/zhangzhong
    ports:
      - "3322:22"
    restart: on-failure
